# Must be unique in a given SonarQube instance
sonar.projectKey=pragnakalpdev80_booking-chatbot-backend
sonar.organization=pragnakalpdev80

# --- optional properties ---

# encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Project configuration
sonar.python.version=3.12
sonar.sources=apps,config
sonar.tests=apps
sonar.test.inclusions=**/test_*.py,**/*_tests.py,**/tests.py
sonar.exclusions=**/migrations/**,**/venv/**,**/.venv/**,**/../venv/**

# Coverage reporting
sonar.python.coverage.reportPaths=coverage.xml
