# Generated by Django 6.0.7 on 2026-07-29 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('session_key', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Client-side session identifier — returned on session creation.', unique=True)),
                ('user_email', models.EmailField(blank=True, db_index=True, default='', help_text='Email collected mid-conversation; used as lookup key for CRUD ops.', max_length=254)),
                ('intent', models.CharField(blank=True, default='', help_text='Current detected intent: book|check|reschedule|cancel|none', max_length=50)),
                ('pending_slot', models.JSONField(blank=True, help_text='Temporarily holds {"start": "...", "end": "..."} awaiting email confirmation.', null=True)),
                ('provider', models.ForeignKey(help_text='The doctor this session is bound to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation Session',
                'verbose_name_plural': 'Conversation Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=20)),
                ('content', models.TextField()),
                ('tool_call_id', models.CharField(blank=True, default='', max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversationsession')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
