# Generated by Django 6.0.7 on 2026-07-29 06:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('mock_order_id', models.CharField(max_length=64, unique=True)),
                ('mock_payment_id', models.CharField(blank=True, max_length=64)),
                ('mock_signature', models.CharField(blank=True, max_length=256)),
                ('session_key', models.UUIDField(db_index=True)),
                ('amount_paise', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired')], default='created', max_length=20)),
                ('payment_url', models.URLField()),
                ('expires_at', models.DateTimeField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='calendar_app.booking')),
            ],
            options={
                'indexes': [models.Index(fields=['mock_order_id'], name='payments_po_orderid_idx'), models.Index(fields=['session_key'], name='payments_po_session_idx'), models.Index(fields=['status', 'expires_at'], name='payments_po_status_exp_idx')],
            },
        ),
    ]
