# Generated by Django 6.0.7 on 2026-07-29 06:58

import common.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('email', models.EmailField(db_index=True, help_text='Email address of the anonymous user who made this booking.', max_length=254)),
                ('name', models.CharField(blank=True, default='', help_text='Optional display name for the calendar event.', max_length=255)),
                ('google_event_id', models.CharField(help_text='Google Calendar event ID — primary reference to the live event.', max_length=255, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reason', models.TextField(blank=True, default='', help_text='Reason for the booking (user-supplied).')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('failed', 'Failed')], default='confirmed', max_length=20)),
                ('provider', models.ForeignKey(help_text='The doctor/provider this appointment is booked with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='GoogleCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('token', common.models.fields.EncryptedTextField(help_text='Encrypted Google OAuth2 token JSON.')),
                ('token_updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.TextField(blank=True, default='', help_text='Space-separated OAuth scopes granted.')),
                ('user', models.OneToOneField(help_text='The admin user who owns this Google Calendar connection.', on_delete=django.db.models.deletion.CASCADE, related_name='google_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Credential',
                'verbose_name_plural': 'Google Credentials',
            },
        ),
        migrations.CreateModel(
            name='ProviderSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('slug', models.SlugField(help_text="URL-safe identifier, e.g. 'drsmith'. Auto-populated from username.", max_length=100, unique=True)),
                ('calendar_id', models.CharField(default='primary', help_text="The Google Calendar ID used for bookings (e.g. 'primary' or 'abc@group.calendar.google.com').", max_length=255)),
                ('provider_name', models.CharField(default='Dr. Smith', help_text='Service/provider name — injected into the chatbot system prompt.', max_length=255)),
                ('day_schedules', models.JSONField(default=dict, help_text="Per-day working hours. Keys are weekday strings '0'–'6'.")),
                ('slot_duration', models.IntegerField(choices=[(15, '15 Minutes'), (30, '30 Minutes'), (45, '45 Minutes'), (60, '60 Minutes')], default=30, help_text='Appointment slot duration in minutes.')),
                ('timezone', models.CharField(default='Asia/Kolkata', help_text='IANA timezone for the clinic (e.g. Asia/Kolkata, America/New_York).', max_length=64)),
                ('payment_required', models.BooleanField(default=False, help_text='If True, users must pay before Google Calendar slot is confirmed.')),
                ('booking_fee_paise', models.PositiveIntegerField(default=10000, help_text='Booking fee in paise (smallest INR unit). 10000 = ₹100.')),
                ('user', models.OneToOneField(help_text='The doctor/provider who owns these settings.', on_delete=django.db.models.deletion.CASCADE, related_name='provider_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Settings',
                'verbose_name_plural': 'Provider Settings',
            },
        ),
        migrations.CreateModel(
            name='BreakTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('weekday', models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')])),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('label', models.CharField(blank=True, default='Break', max_length=100)),
                ('provider_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_times', to='calendar_app.providersettings')),
            ],
            options={
                'ordering': ['weekday', 'start'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(db_index=True)),
                ('label', models.CharField(blank=True, default='Holiday', max_length=255)),
                ('provider_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='calendar_app.providersettings')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('provider_settings', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SlotLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('session_key', models.UUIDField(blank=True, db_index=True, help_text='The session key that holds this lock.', null=True)),
                ('slot_start', models.DateTimeField(db_index=True)),
                ('slot_end', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_confirmed', models.BooleanField(db_index=True, default=False, help_text='True if the user successfully booked this slot. The lock is then ignored.')),
                ('provider', models.ForeignKey(help_text='The doctor/provider this slot lock is for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Slot Lock',
                'verbose_name_plural': 'Slot Locks',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_confirmed', False)), fields=('slot_start', 'provider'), name='unique_active_slot_lock_per_provider')],
            },
        ),
    ]
