# Generated by Django 6.0.7 on 2026-07-22 10:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Email address of the anonymous user who made this booking.', max_length=254)),
                ('name', models.CharField(blank=True, default='', help_text='Optional display name for the calendar event.', max_length=255)),
                ('google_event_id', models.CharField(help_text='Google Calendar event ID — primary reference to the live event.', max_length=255, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reason', models.TextField(blank=True, default='', help_text='Reason for the booking (user-supplied).')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(default='Dr. Smith', help_text='Service/provider name — injected into the chatbot system prompt.', max_length=255)),
                ('work_days', models.JSONField(default=list, help_text='List of weekday integers (0=Mon … 6=Sun) when the clinic is open.')),
                ('work_start', models.TimeField(default=datetime.time(9, 0), help_text='Start of working hours (local time).')),
                ('work_end', models.TimeField(default=datetime.time(17, 0), help_text='End of working hours (local time).')),
                ('slot_duration', models.IntegerField(default=30, help_text='Appointment slot duration in minutes. Always 30.')),
                ('timezone', models.CharField(default='Asia/Kolkata', help_text='IANA timezone for the clinic (e.g. Asia/Kolkata, America/New_York).', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider Settings',
                'verbose_name_plural': 'Provider Settings',
            },
        ),
        migrations.CreateModel(
            name='GoogleCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='Encrypted Google OAuth2 token JSON.')),
                ('token_updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.TextField(blank=True, default='', help_text='Space-separated OAuth scopes granted.')),
                ('user', models.OneToOneField(help_text='The admin user who owns this Google Calendar connection.', on_delete=django.db.models.deletion.CASCADE, related_name='google_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Credential',
                'verbose_name_plural': 'Google Credentials',
            },
        ),
    ]
