# Generated by Django 6.0.7 on 2026-07-30 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='slotlock',
            name='unique_active_slot_lock_per_provider',
        ),
        migrations.AddField(
            model_name='slotlock',
            name='is_expired',
            field=models.BooleanField(db_index=True, default=False, help_text='True if the 15-minute reservation window timed out without being confirmed. Soft-expiry keeps the row so the agent can report the expiry to the user even after the Celery cleanup task runs.'),
        ),
        migrations.AddConstraint(
            model_name='slotlock',
            constraint=models.UniqueConstraint(condition=models.Q(('is_confirmed', False), ('is_expired', False)), fields=('slot_start', 'provider'), name='unique_active_slot_lock_per_provider'),
        ),
    ]
