# Generated by Django 6.0.7 on 2026-07-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(blank=True, db_index=True, help_text='The session key that holds this lock.', null=True)),
                ('slot_start', models.DateTimeField(db_index=True)),
                ('slot_end', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(db_index=True, default=False, help_text='True if the user successfully booked this slot. The lock is then ignored.')),
            ],
            options={
                'verbose_name': 'Slot Lock',
                'verbose_name_plural': 'Slot Locks',
                'ordering': ['-locked_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_confirmed', False)), fields=('slot_start',), name='unique_active_slot_lock')],
            },
        ),
    ]
