# Generated by Django 6.0.7 on 2026-07-24 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_slotlock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='slotlock',
            name='unique_active_slot_lock',
        ),
        migrations.AddField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(help_text='The doctor/provider this appointment is booked with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='calendar_id',
            field=models.CharField(default='primary', help_text="The Google Calendar ID used for bookings (e.g. 'primary' or 'abc@group.calendar.google.com').", max_length=255),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='user',
            field=models.OneToOneField(default=1, help_text='The doctor/provider who owns these settings.', on_delete=django.db.models.deletion.CASCADE, related_name='provider_settings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slotlock',
            name='provider',
            field=models.ForeignKey(help_text='The doctor/provider this slot lock is for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_locks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='slotlock',
            constraint=models.UniqueConstraint(condition=models.Q(('is_confirmed', False)), fields=('slot_start', 'provider'), name='unique_active_slot_lock_per_provider'),
        ),
    ]
