# Generated by Django 6.0.7 on 2026-07-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_remove_slotlock_unique_active_slot_lock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersettings',
            name='booking_fee_paise',
            field=models.PositiveIntegerField(default=10000, help_text='Booking fee in paise (smallest INR unit). 10000 = ₹100.'),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='payment_required',
            field=models.BooleanField(default=False, help_text='If True, users must pay before Google Calendar slot is confirmed.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='confirmed', max_length=20),
        ),
    ]
