# Generated by Django 6.0.7 on 2026-07-27 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_providersettings_booking_fee_paise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providersettings',
            name='work_days',
        ),
        migrations.RemoveField(
            model_name='providersettings',
            name='work_end',
        ),
        migrations.RemoveField(
            model_name='providersettings',
            name='work_start',
        ),
        migrations.AddField(
            model_name='providersettings',
            name='day_schedules',
            field=models.JSONField(default=dict, help_text="Per-day working hours. Keys are weekday strings '0'–'6'."),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('failed', 'Failed')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='providersettings',
            name='slot_duration',
            field=models.IntegerField(choices=[(15, '15 Minutes'), (30, '30 Minutes'), (45, '45 Minutes'), (60, '60 Minutes')], default=30, help_text='Appointment slot duration in minutes.'),
        ),
        migrations.CreateModel(
            name='BreakTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')])),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('label', models.CharField(blank=True, default='Break', max_length=100)),
                ('provider_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_times', to='calendar_app.providersettings')),
            ],
            options={
                'ordering': ['weekday', 'start'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('label', models.CharField(blank=True, default='Holiday', max_length=255)),
                ('provider_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='calendar_app.providersettings')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('provider_settings', 'date')},
            },
        ),
    ]
