# Generated by Django 6.0.7 on 2026-07-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_remove_providersettings_work_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersettings',
            name='slug',
            field=models.SlugField(blank=True, help_text="URL-safe identifier, e.g. 'drsmith'. Auto-populated from username.", max_length=100, null=True, unique=True),
        ),
    ]
