# Generated by Django 6.0.7 on 2026-07-27 10:44

import django.utils.text
from django.db import migrations

def backfill_slugs(apps, schema_editor):
    ProviderSettings = apps.get_model('calendar_app', 'ProviderSettings')
    for settings in ProviderSettings.objects.all():
        if not settings.slug:
            settings.slug = django.utils.text.slugify(settings.user.username)
            settings.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_providersettings_slug'),
    ]

    operations = [
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
    ]
