# Generated by Django 6.0.7 on 2026-07-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0007_backfill_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providersettings',
            name='slug',
            field=models.SlugField(help_text="URL-safe identifier, e.g. 'drsmith'. Auto-populated from username.", max_length=100, unique=True),
        ),
    ]
